// generated by scripts/build/tokens.mjs from content/tokens.json. Do not edit.
// Named exports so a bundle keeps only what it reads.
export const springs = /*#__PURE__*/ Object.freeze({
  "press": {
    "hz": 4,
    "zeta": 0.7,
    "mass": 1,
    "stiffness": 631.7,
    "damping": 35.19,
    "overshootPct": 4.6,
    "settle2Ms": 237,
    "cssLinearMs": 410,
    "css": "linear(0, 0.0294, 0.1036, 0.2051, 0.3198, 0.4375, 0.5508, 0.6546, 0.7461, 0.824, 0.8881, 0.9389, 0.9778, 1.0061, 1.0255, 1.0376, 1.044, 1.046, 1.0448, 1.0415, 1.0369, 1.0317, 1.0263, 1.021, 1.0162, 1.012, 1.0083, 1.0054, 1.003, 1.0011, 0.9998, 0.9989, 0.9983, 0.998, 0.9979, 0.9979, 0.9981, 0.9983, 0.9985, 0.9988, 1)"
  },
  "detent": {
    "hz": 3.2,
    "zeta": 0.6,
    "mass": 1,
    "stiffness": 404.3,
    "damping": 24.13,
    "overshootPct": 9.5,
    "settle2Ms": 295,
    "cssLinearMs": 510,
    "css": "linear(0, 0.0296, 0.1059, 0.2123, 0.3349, 0.4624, 0.5864, 0.7009, 0.8018, 0.8872, 0.9563, 1.0096, 1.0482, 1.0739, 1.0886, 1.0945, 1.0934, 1.0874, 1.0781, 1.0668, 1.0548, 1.0429, 1.0317, 1.0217, 1.0131, 1.0061, 1.0005, 0.9965, 0.9937, 0.9919, 0.9911, 0.9911, 0.9915, 0.9923, 0.9933, 0.9944, 0.9956, 0.9967, 0.9977, 0.9985, 1)"
  },
  "settle": {
    "hz": 2.6,
    "zeta": 0.82,
    "mass": 1,
    "stiffness": 266.9,
    "damping": 26.79,
    "overshootPct": 1.1,
    "settle2Ms": 239,
    "cssLinearMs": 530,
    "css": "linear(0, 0.0208, 0.0739, 0.1474, 0.2325, 0.3224, 0.412, 0.4979, 0.5779, 0.6505, 0.7152, 0.7717, 0.8204, 0.8615, 0.8958, 0.9239, 0.9466, 0.9647, 0.9787, 0.9894, 0.9973, 1.0029, 1.0068, 1.0092, 1.0105, 1.0111, 1.011, 1.0105, 1.0098, 1.0089, 1.0079, 1.0069, 1.0059, 1.005, 1.0042, 1.0034, 1.0027, 1.0022, 1.0017, 1.0013, 1)"
  },
  "lag": {
    "hz": 1.8,
    "zeta": 0.75,
    "mass": 1,
    "stiffness": 127.9,
    "damping": 16.96,
    "overshootPct": 2.8,
    "settle2Ms": 507,
    "cssLinearMs": 710,
    "css": "linear(0, 0.0182, 0.0657, 0.1333, 0.2134, 0.2999, 0.3882, 0.4748, 0.557, 0.6333, 0.7024, 0.7639, 0.8176, 0.8636, 0.9024, 0.9345, 0.9606, 0.9812, 0.9971, 1.009, 1.0175, 1.0231, 1.0265, 1.0281, 1.0283, 1.0275, 1.0259, 1.0239, 1.0215, 1.019, 1.0165, 1.0141, 1.0118, 1.0097, 1.0078, 1.0062, 1.0047, 1.0035, 1.0024, 1.0016, 1)"
  }
});

export const durations = /*#__PURE__*/ Object.freeze({
  "shutter": 130,
  "flash": 350,
  "flashMinGap": 1000,
  "eject": 800,
  "hang": 240,
  "developHero": 2600,
  "develop": 2400,
  "developSheet": 1600,
  "sheetStagger": 60,
  "regrade": 1200,
  "pencilDraw": 420,
  "pencilStagger": 90,
  "panelIn": 220,
  "panelOut": 160,
  "posterFade": 200,
  "glHandback": 120,
  "listToggle": 160,
  "swell": 180,
  "meshReveal": 700,
  "meshRevealLite": 500,
  "handoffPress": 130,
  "handoffDripStart": 200,
  "handoffDrip": 520,
  "handoffNavigate": 720,
  "handoffCancel": 200,
  "reduced": 200,
  "idleDetach": 1000,
  "bootProbeMax": 500
});

export const heroTimeline = /*#__PURE__*/ Object.freeze({
  "t0AfterGlReady": 200,
  "brackets": 0,
  "shutter": 120,
  "flash": 250,
  "eject": 380,
  "developStart": 780,
  "flight": 1180,
  "landingDip": 1620,
  "readable": 1804,
  "developed": 3380,
  "readableAfterGlReady": 2004,
  "budgetAfterGlReady": 2100
});

export const develop = /*#__PURE__*/ Object.freeze({
  "curve": "d = 1 - (1 - t)^2.4",
  "readableAt": 0.7,
  "readableFractionOfDuration": 0.394
});

export const ease = /*#__PURE__*/ Object.freeze({
  "out": "cubic-bezier(0.23, 1, 0.32, 1)",
  "inOutCubic": "cubic-bezier(0.65, 0, 0.35, 1)"
});

export const z = /*#__PURE__*/ Object.freeze({
  "ground": 0,
  "gl": 1,
  "content": 2,
  "chrome": 10,
  "overlay": 35,
  "flash": 40,
  "glRaisedForDrip": 41,
  "skip": 50
});

export const breakpoints = /*#__PURE__*/ Object.freeze({
  "B1": "max 479px",
  "B2": "480-767px",
  "B3": "768-1023px",
  "B4": "1024-1439px",
  "B5": "min 1440px",
  "sm": "30rem",
  "md": "48rem",
  "lg": "64rem",
  "xl": "90rem",
  "heroSplit": "(min-width: 64rem), (orientation: landscape) and (max-height: 500px)",
  "listDefault": "(max-width: 47.99rem) or static tier or Save-Data"
});

export const tiers = /*#__PURE__*/ Object.freeze({
  "full": "WebGL2, (pointer: fine) and (hover: hover), no Save-Data, boot probe median <= 8 ms (3 wet hero prints, 30 frames, readPixels fences); DPR <= 2, canvas <= 4.5 Mpx, MSAA",
  "lite": "other WebGL2; DPR <= 1.5, canvas <= 1.5 Mpx, no MSAA, LITE shader, GL boot on intent",
  "static": "no WebGL2, 2 context losses in 60 s, or second governor step",
  "governor": "45 busy frames averaging > 22 ms step down one tier, never up",
  "never": "navigator.hardwareConcurrency, maxTouchPoints",
  "override": "?tier=full|lite|static"
});

export const stage = /*#__PURE__*/ Object.freeze({
  "projection": "stage-local scissored viewport per [data-gl=object] slot; prints keep the page camera (1 GL unit = 1 CSS px)",
  "fovDeg": 28,
  "poses": {
    "split": {
      "yawDeg": -24,
      "pitchDeg": 12
    },
    "stacked": {
      "yawDeg": -20,
      "pitchDeg": 10
    },
    "phone": {
      "yawDeg": -16,
      "pitchDeg": 8
    },
    "tuning": "W-C14 may tune within 5 degrees, then posters are re-rendered"
  },
  "lod": "LOD0 when projected width >= 600 device px and tier != static, else LOD1",
  "heroRow": {
    "copyCols": "5/12",
    "stageCols": "7/12",
    "stageHeight": "min(content width, 100svh minus the text stack)",
    "print1MinBelow64rem": "50% of content width",
    "print1WindowMinAt64rem": "220px"
  }
});

export const layout = /*#__PURE__*/ Object.freeze({
  "enlargementsPctOfContent": {
    "B1-B2": [
      70,
      62,
      66
    ],
    "B3": [
      52,
      44,
      46
    ],
    "B4-B5": [
      34,
      27,
      24
    ],
    "maxPx": 600
  },
  "captions": "below under 1024, beside at 1024+, never over images",
  "sheetColumns": {
    "B1-B2": 2,
    "B3": 3,
    "B4-B5": 4
  },
  "minPrintPx": 140,
  "phoneSheet": "alternate columns offset 24px, seeded tilt up to 1.5deg",
  "doorPhoneMaxScreens": 0.8
});

export const monogram = /*#__PURE__*/ Object.freeze({
  "source": "Bricolage Grotesque bracketleft/bracketright, opsz 96, wght 800",
  "stem": 0.179,
  "arm": 0.148,
  "reach": 0.289,
  "aperture": 0.742,
  "clearSpace": 0.5,
  "minHeightPx": 12,
  "favicon16": "stem 2, arm 2, reach 3, window 6x8",
  "cameraPlacement": "strap tag ([d64], per D-011) and print border ([ ]); never on the camera body, which keeps FUJIFILM and X-T5 lettering"
});

export const filmLooks = /*#__PURE__*/ Object.freeze({
  "ids": [
    "standard",
    "candle",
    "vivid",
    "mono",
    "cyanotype"
  ],
  "status": "provisional (W-D018)",
  "contract": "Manor _IonFilmR/G/B/P; P.x S-curve weight (0 identity), P.y grain, P.z lift, P.w mix"
});

export const predicates = /*#__PURE__*/ Object.freeze({
  "canEnterManor": "WebGL2 && matchMedia('(any-pointer: fine) and (any-hover: hover)').matches && !navigator.connection?.saveData",
  "heroEject": "matchMedia('(pointer: fine) and (hover: hover)') && 'WebGL2RenderingContext' in window && !reducedMotion && !saveData",
  "note": "no width terms; width changes layout only"
});

export const colour = /*#__PURE__*/ Object.freeze({
  "light": {
    "table": "#E3E6E6",
    "table-lit": "#EEF0EF",
    "paper": "#F6F5F1",
    "proof": "#E7EAE9",
    "rule": "#BFC6C8",
    "ink": "#13171A",
    "ink-2": "#444D52"
  },
  "dark": {
    "table": "#14181A",
    "table-lit": "#1C2225",
    "paper": "#E7E6E1",
    "rule": "#2C3438",
    "ink": "#E9ECEA",
    "ink-2": "#A9B2B5",
    "note": "proof and paper stay light in the dark scheme (they are paper); focus colour follows the surface"
  },
  "door": {
    "darkroom": "#14100E",
    "on-dark": "#ECE8E0",
    "on-dark-2": "#B9B3A9",
    "on-dark-3": "#9C968C",
    "darkSchemeBoundary": "1 px amber rule plus a 6% safelight wash at the door's top edge; dark table vs darkroom measures 1.06:1, so the boundary must be drawn"
  },
  "accent": {
    "amber": "#E39B2B",
    "amberDeep": "#875802",
    "onAccent": "#13171A",
    "brass": "#C59A45"
  }
});

export const MOTION_KEY = 'ion.motion';

/** The one Manor predicate (W-D021); the same function text as can-enter-manor.js. */
export const canEnterManor = function(){try{var c=navigator.connection;if(!window.WebGL2RenderingContext||!matchMedia("(any-pointer: fine) and (any-hover: hover)").matches||c&&c.saveData)return!1;var g=document.createElement("canvas").getContext("webgl2"),x=g&&g.getExtension("WEBGL_lose_context");x&&x.loseContext();return!!g}catch(e){return!1}};
